## 練習時間
假設我們資料中類別的數量並不均衡，在評估準確率時可能會有所偏頗，試著切分出 y_test 中，0 類別與 1 類別的數量是一樣的 (亦即 y_test 的類別是均衡的)

In [26]:
import numpy as np
X = np.arange(1000).reshape(200, 5)
y = np.zeros(200)
y[:40] = 1

In [27]:
y

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

可以看見 y 類別中，有 160 個 類別 0，40 個 類別 1 ，請試著使用 train_test_split 函數，切分出 y_test 中能各有 10 筆類別 0 與 10 筆類別 1 。(HINT: 參考函數中的 test_size，可針對不同類別各自作切分後再合併)

In [28]:
from sklearn.model_selection import train_test_split, KFold
y_index0 = []
y_index1 = []
j = 0
for i in y:
    if i == 0:
        y_index0.append(j)
    else:
        y_index1.append(j)
    j = j + 1

X_train_0, X_test_0, y_train_0, y_test_0 = train_test_split(X[y_index0], y[y_index0], test_size=10)
X_train_1, X_test_1, y_train_1, y_test_1 = train_test_split(X[y_index1], y[y_index1], test_size=0.25)

In [29]:
print('y_test_0:{0}'.format(y_test_0))
print('X_test_0:{0}'.format(X_test_0))

y_test_0:[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
X_test_0:[[635 636 637 638 639]
 [315 316 317 318 319]
 [740 741 742 743 744]
 [925 926 927 928 929]
 [815 816 817 818 819]
 [455 456 457 458 459]
 [860 861 862 863 864]
 [600 601 602 603 604]
 [450 451 452 453 454]
 [345 346 347 348 349]]


In [30]:
y_test_1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [31]:
y_test = np.append(y_test_0, y_test_1)
y_test

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [32]:
X_test = np.append(X_test_0, X_test_1)
X_test

array([635, 636, 637, 638, 639, 315, 316, 317, 318, 319, 740, 741, 742,
       743, 744, 925, 926, 927, 928, 929, 815, 816, 817, 818, 819, 455,
       456, 457, 458, 459, 860, 861, 862, 863, 864, 600, 601, 602, 603,
       604, 450, 451, 452, 453, 454, 345, 346, 347, 348, 349, 125, 126,
       127, 128, 129, 140, 141, 142, 143, 144,  70,  71,  72,  73,  74,
        80,  81,  82,  83,  84,  95,  96,  97,  98,  99, 170, 171, 172,
       173, 174,  85,  86,  87,  88,  89,  65,  66,  67,  68,  69, 135,
       136, 137, 138, 139,  45,  46,  47,  48,  49])